# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1309ae546e3ff29ce6c5c314f78a13a53259afd8e79d0b03b6ec50812c2216f098d3c9d3b0af535404ebfef1345f90ab4b653a3f8cc3f7b92f682262570d4cf1

test:
  secret_key_base: 5c4afb3390b4d5dbea5e4989c409ab349f25d19e5693cd8499e1c5067d69ade79bcd9d9ad1e46920c6b95df0793d1fd4d9aa0503f3799b96fcbf842b297da114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
